# Generated by Django 5.1.2 on 2024-11-01 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.IntegerField()),
                ('branch_name', models.CharField(max_length=100, unique=True)),
                ('branch_Category', models.CharField(default=None, max_length=100)),
                ('branch_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='Null', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allias', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('qualification_type', models.CharField(blank=True, choices=[('Professional', 'Professional'), ('Educational', 'Educational')], default='Educational', max_length=20, null=True)),
                ('institution', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('functional_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='core.functionalgroup')),
            ],
        ),
        migrations.AddField(
            model_name='functionalgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_groups', to='core.group'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('cnic_no', models.CharField(max_length=13, unique=True)),
                ('husband_or_father_name', models.CharField(max_length=100)),
                ('SAP_ID', models.IntegerField(default=None, unique=True)),
                ('date_of_last_promotion', models.DateField(default='1900', max_length=15)),
                ('date_current_posting', models.DateField(default='1900', max_length=15)),
                ('date_current_assignment', models.DateField(default='1900', max_length=15)),
                ('mobile_no', models.CharField(blank=True, default='1111', max_length=15, null=True)),
                ('phone_no_official', models.CharField(blank=True, default='1111', max_length=15, null=True)),
                ('phone_no_emergency_contact', models.CharField(blank=True, default='1111', max_length=15, null=True)),
                ('employee_email', models.EmailField(blank=True, default='aa@aa.aa', max_length=100, null=True)),
                ('date_of_retirement', models.DateField(blank=True, default='1900', null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.branch', to_field='branch_name')),
                ('cadre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cadre')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.designation', to_field='title')),
                ('employee_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employeegrade', to_field='grade_name')),
                ('employee_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employeetype', to_field='name')),
                ('qualifications', models.ManyToManyField(related_name='employees', to='core.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region_category', models.CharField(blank=True, max_length=100, null=True)),
                ('functional_group', models.ManyToManyField(related_name='regions', to='core.functionalgroup')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.region'),
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wings', to='core.division', to_field='name')),
            ],
        ),
    ]
