# Generated by Django 5.1.2 on 2024-11-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionalgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_groups', to='core.group', to_field='name'),
        ),
    ]
