# Generated by Django 5.1.2 on 2024-10-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionalgroup',
            name='description',
        ),
        migrations.AddField(
            model_name='functionalgroup',
            name='allias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='description',
            field=models.TextField(blank=True, default='Null', null=True),
        ),
    ]
