# Generated by Django 5.1.2 on 2024-10-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_app', '0003_rename_description_region_region_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='functional_group',
        ),
        migrations.AlterField(
            model_name='region',
            name='region_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='functional_group',
            field=models.ManyToManyField(related_name='regions', to='HRMS_app.functionalgroup'),
        ),
    ]
