# Generated by Django 5.1.2 on 2024-10-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_app', '0004_remove_region_functional_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_Category',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
