# Generated by Django 5.1.2 on 2024-10-31 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_app', '0006_alter_division_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
