# Generated by Django 5.1.2 on 2024-10-31 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_app', '0007_remove_employee_department_delete_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_current_assignment',
            field=models.DateField(default='1900', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_current_posting',
            field=models.DateField(default='1900', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_last_promotion',
            field=models.DateField(default='1900', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(blank=True, default='1900', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_email',
            field=models.EmailField(blank=True, default='aa@aa.aa', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_no',
            field=models.CharField(blank=True, default='1111', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_no_emergency_contact',
            field=models.CharField(blank=True, default='1111', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_no_official',
            field=models.CharField(blank=True, default='1111', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='wing',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wings', to='HRMS_app.division', to_field='name'),
        ),
    ]
