# Generated by Django 5.1.2 on 2024-11-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_app', '0011_alter_employee_employee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
    ]
